//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsix.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vsix.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c# project.
        /// </summary>
        internal static string cs_project {
            get {
                return ResourceManager.GetString("cs_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select C# project for template.
        /// </summary>
        internal static string cs_project_title {
            get {
                return ResourceManager.GetString("cs_project_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Getting Started&apos; Guide.
        /// </summary>
        internal static string gettingStarted_title {
            get {
                return ResourceManager.GetString("gettingStarted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        internal static string icon_file {
            get {
                return ResourceManager.GetString("icon_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Icon.
        /// </summary>
        internal static string icon_title {
            get {
                return ResourceManager.GetString("icon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select License.
        /// </summary>
        internal static string license_title {
            get {
                return ResourceManager.GetString("license_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsix Manifest.
        /// </summary>
        internal static string ManifestWindowLabel {
            get {
                return ResourceManager.GetString("ManifestWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Installed Vsix.
        /// </summary>
        internal static string menuAboutInstalledVsix {
            get {
                return ResourceManager.GetString("menuAboutInstalledVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Vsix package.
        /// </summary>
        internal static string menuAboutRemoveVsix {
            get {
                return ResourceManager.GetString("menuAboutRemoveVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Vsix package.
        /// </summary>
        internal static string menuAboutVsix {
            get {
                return ResourceManager.GetString("menuAboutVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error Report/comments.
        /// </summary>
        internal static string menuErrorReport {
            get {
                return ResourceManager.GetString("menuErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string menuNewVsix {
            get {
                return ResourceManager.GetString("menuNewVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string menuOpenVsix {
            get {
                return ResourceManager.GetString("menuOpenVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string menuOptions {
            get {
                return ResourceManager.GetString("menuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string menuSaveVsix {
            get {
                return ResourceManager.GetString("menuSaveVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        internal static string menuSetLanguage {
            get {
                return ResourceManager.GetString("menuSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Bindings in xaml files.
        /// </summary>
        internal static string menuViewBindings {
            get {
                return ResourceManager.GetString("menuViewBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        internal static string menuViewLog {
            get {
                return ResourceManager.GetString("menuViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Styles (StaticResource, DynamicResource) in xaml files.
        /// </summary>
        internal static string menuViewStyles {
            get {
                return ResourceManager.GetString("menuViewStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Preview Image.
        /// </summary>
        internal static string preivewImage_title {
            get {
                return ResourceManager.GetString("preivewImage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text file.
        /// </summary>
        internal static string text_file {
            get {
                return ResourceManager.GetString("text_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string TextAuthorLabel {
            get {
                return ResourceManager.GetString("TextAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        internal static string TextBrowseLabel {
            get {
                return ResourceManager.GetString("TextBrowseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest Version.
        /// </summary>
        internal static string TextManifestVersionLabel {
            get {
                return ResourceManager.GetString("TextManifestVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string TextMetadataLabel {
            get {
                return ResourceManager.GetString("TextMetadataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string TextProductIDLabel {
            get {
                return ResourceManager.GetString("TextProductIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string TextProductNameLabel {
            get {
                return ResourceManager.GetString("TextProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csproj Path.
        /// </summary>
        internal static string TextProjectCsPathLabel {
            get {
                return ResourceManager.GetString("TextProjectCsPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Guid.
        /// </summary>
        internal static string TextRefreshGuidLabel {
            get {
                return ResourceManager.GetString("TextRefreshGuidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string TextVersionLabel {
            get {
                return ResourceManager.GetString("TextVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TextVsixDescriptionLabel {
            get {
                return ResourceManager.GetString("TextVsixDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started Guide.
        /// </summary>
        internal static string TextVsixGettingStartedGuideLabel {
            get {
                return ResourceManager.GetString("TextVsixGettingStartedGuideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string TextVsixIconLabel {
            get {
                return ResourceManager.GetString("TextVsixIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string TextVsixLicenseLabel {
            get {
                return ResourceManager.GetString("TextVsixLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info URL.
        /// </summary>
        internal static string TextVsixMoreInfoURLLabel {
            get {
                return ResourceManager.GetString("TextVsixMoreInfoURLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Image.
        /// </summary>
        internal static string TextVsixPreviewImageLabel {
            get {
                return ResourceManager.GetString("TextVsixPreviewImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        internal static string TextVsixReleaseNotesLabel {
            get {
                return ResourceManager.GetString("TextVsixReleaseNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string TextVsixTagsLabel {
            get {
                return ResourceManager.GetString("TextVsixTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsix Editor.
        /// </summary>
        internal static string VsixEditorTitle {
            get {
                return ResourceManager.GetString("VsixEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web file.
        /// </summary>
        internal static string web_file {
            get {
                return ResourceManager.GetString("web_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word file.
        /// </summary>
        internal static string word_file {
            get {
                return ResourceManager.GetString("word_file", resourceCulture);
            }
        }
    }
}
